Create Stakingasawayout.md
citizen-cosmos/blog pull request #25
Opened 2022-07-14 08:21 UTC by Cosmopusk

New article

2022-07-14 11:00 UTC, serejandmyself requested changes
- there is no single link in the article - plz add

- do not use CAPS

2022-07-15 13:21 UTC, serejandmyself requested changes
Same comments:

- Please add links and embed them

2022-07-15 14:54 UTC, Cosmopusk commented
I added links and changed tag line. What do you think?

2022-07-17 10:40 UTC, serejandmyself approved these changes

2022-07-18 14:36 UTC, merged