Create ICS.md
citizen-cosmos/blog pull request #50
Opened 2022-08-09 10:12 UTC by Cosmopusk

2022-08-11 19:21 UTC, Voskodan approved these changes

2022-08-12 09:38 UTC, spotlessmind1 requested changes
Should add dates and more info when it will be implemented in cosmos https://twitter.com/EncryptionDog/status/1557800692126990337

2022-08-12 12:15 UTC, Cosmopusk commented
Done

2022-08-12 12:22 UTC, spotlessmind1 requested changes
Need to revise text for future. It is not happened yet. And add more detailed roadmap info about launching - some more facts...

2022-08-12 19:18 UTC, spotlessmind1 approved these changes

2022-08-12 19:18 UTC, merged